# Generated by Django 2.2 on 2019-08-09 23:05

import autoslug.fields
import django.contrib.postgres.fields.jsonb
import django.contrib.postgres.fields.ranges
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Investment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('realestate', 'Real estate'), ('p2plending', 'P2P lending'), ('business', 'Business'), ('precious', 'Precious objects'), ('hedge', 'Hedge funds'), ('bond', 'Bonds'), ('commodity', 'Commodities'), ('equity', 'Equities')], max_length=15)),
                ('title', models.CharField(max_length=200)),
                ('title_it', models.CharField(max_length=200, null=True)),
                ('title_en', models.CharField(max_length=200, null=True)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='title', unique=True)),
                ('slug_it', autoslug.fields.AutoSlugField(editable=False, null=True, populate_from='title', unique=True)),
                ('slug_en', autoslug.fields.AutoSlugField(editable=False, null=True, populate_from='title', unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('description_it', models.TextField(blank=True, null=True)),
                ('description_en', models.TextField(blank=True, null=True)),
                ('url', models.URLField(blank=True, max_length=250, null=True)),
                ('source', models.CharField(choices=[('caseinpiemonte', 'Case in Piemonte'), ('remicom', 'Remicom'), ('exploresardinia', 'Explore Sardinia'), ('sestrierecase', 'Sestriere case'), ('manual', 'Manuale')], default='manual', max_length=15)),
                ('countries', django_countries.fields.CountryField(default='IT', max_length=26, multiple=True)),
                ('interest', django.contrib.postgres.fields.ranges.DecimalRangeField(null=True)),
                ('price', django.contrib.postgres.fields.ranges.DecimalRangeField(null=True)),
                ('currency', models.CharField(blank=True, max_length=3, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Bond',
            fields=[
                ('investment_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='investments.Investment')),
            ],
            options={
                'verbose_name': 'Bond investment',
                'verbose_name_plural': 'Bonds investments',
            },
            bases=('investments.investment',),
        ),
        migrations.CreateModel(
            name='Business',
            fields=[
                ('investment_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='investments.Investment')),
                ('address', models.CharField(max_length=500, null=True)),
                ('surface', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('raw_data', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
                ('identifier', models.CharField(blank=True, max_length=200, null=True, unique=True)),
            ],
            options={
                'verbose_name': 'Business investment',
                'verbose_name_plural': 'Business investments',
            },
            bases=('investments.investment',),
        ),
        migrations.CreateModel(
            name='Commodity',
            fields=[
                ('investment_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='investments.Investment')),
            ],
            options={
                'verbose_name': 'Commodity investment',
                'verbose_name_plural': 'Commodities investments',
            },
            bases=('investments.investment',),
        ),
        migrations.CreateModel(
            name='Equity',
            fields=[
                ('investment_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='investments.Investment')),
            ],
            options={
                'verbose_name': 'Equity investment',
                'verbose_name_plural': 'Equities investments',
            },
            bases=('investments.investment',),
        ),
        migrations.CreateModel(
            name='HedgeFund',
            fields=[
                ('investment_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='investments.Investment')),
            ],
            options={
                'verbose_name': 'Hedge fund investment',
                'verbose_name_plural': 'Hedge funds investments',
            },
            bases=('investments.investment',),
        ),
        migrations.CreateModel(
            name='P2PLending',
            fields=[
                ('investment_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='investments.Investment')),
                ('buyback', models.BooleanField()),
            ],
            options={
                'verbose_name': 'Peer to peer lending investment',
                'verbose_name_plural': 'Peer to peer lending investments',
            },
            bases=('investments.investment',),
        ),
        migrations.CreateModel(
            name='PreciousObject',
            fields=[
                ('investment_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='investments.Investment')),
            ],
            options={
                'verbose_name': 'Precious object investment',
                'verbose_name_plural': 'Precious objects investments',
            },
            bases=('investments.investment',),
        ),
        migrations.CreateModel(
            name='RealEstate',
            fields=[
                ('investment_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='investments.Investment')),
                ('address', models.CharField(max_length=500, null=True)),
                ('surface', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('raw_data', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
                ('identifier', models.CharField(blank=True, max_length=200, null=True, unique=True)),
            ],
            options={
                'verbose_name': 'Real estate investment',
                'verbose_name_plural': 'Real estate investments',
            },
            bases=('investments.investment',),
        ),
        migrations.CreateModel(
            name='InvestmentImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='uploads/investments')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('identifier', models.CharField(blank=True, max_length=200, null=True, unique=True)),
                ('investments', models.ManyToManyField(related_name='images', to='investments.Investment')),
            ],
            options={
                'verbose_name': 'Investment image',
                'verbose_name_plural': 'Investment images',
            },
        ),
    ]
