# Generated by Django 2.2b1 on 2019-03-14 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0002_auto_20190219_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investment',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
    ]
