# Generated by Django 2.2b1 on 2019-03-14 23:51

from django.db import migrations
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0003_auto_20190315_0013'),
    ]

    operations = [
        migrations.AddField(
            model_name='investment',
            name='image',
            field=sorl.thumbnail.fields.ImageField(null=True, upload_to='media'),
        ),
    ]
