# Generated by Django 2.2b1 on 2019-03-14 23:54

from django.db import migrations
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0004_investment_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investment',
            name='image',
            field=sorl.thumbnail.fields.ImageField(null=True, upload_to=''),
        ),
    ]
