# Generated by Django 2.2b1 on 2019-03-14 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0004_investment_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investment',
            name='image',
            field=models.ImageField(upload_to="uploads/investments"),
        ),
    ]
