# Generated by Django 2.2b1 on 2019-03-23 17:38
import uuid

import autoslug.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations
from django.db import models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0005_auto_20190315_0054'),
    ]

    operations = [
        migrations.CreateModel(
            name='RealEstateInvestment',
            fields=[
                ('investment_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='investments.Investment')),
                ('address', models.CharField(max_length=500)),
                ('efficency', models.CharField(max_length=2)),
            ],
            bases=('investments.investment',),
        ),
        migrations.RemoveField(
            model_name='investment',
            name='image',
        ),
        migrations.AddField(
            model_name='investment',
            name='category',
            field=models.CharField(choices=[('immobili', 'Immobili'), ('finanza', 'Finanza')], default='immobili', max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='investment',
            name='currency',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='investment',
            name='identifier',
            field=models.CharField(default=uuid.uuid4, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='investment',
            name='meta',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='investment',
            name='source',
            field=models.CharField(choices=[('caseinpiemonte', 'Case in Piemonte'), ('remicom', 'Remicom')], default='caseinpiemonte', max_length=15),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='InvestmentImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='title')),
                ('image', models.ImageField(upload_to='')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('investment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='investments.Investment')),
            ],
        ),
    ]
