# Generated by Django A.B on YYYY-MM-DD HH:MM

import uuid

from django.db import migrations


def gen_uuid(apps, schema_editor):
    Investment = apps.get_model('investments', 'Investment')
    for row in Investment.objects.all():
        row.identifier = uuid.uuid4()
        row.save(update_fields=['identifier'])


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0006_auto_20190323_1838'),
    ]

    operations = [
        # omit reverse_code=... if you don't want the migration to be reversible.
        migrations.RunPython(gen_uuid, reverse_code=migrations.RunPython.noop),
    ]
