# Generated by Django 2.2b1 on 2019-03-23 18:22

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0008_auto_20190323_1856'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RealEstateInvestment',
        ),
        migrations.AddField(
            model_name='investment',
            name='address',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='investment',
            name='efficency',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='investment',
            name='tags',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
    ]
