# Generated by Django 2.2b1 on 2019-03-23 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0009_auto_20190323_1922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investment',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True),
        ),
    ]
