# Generated by Django 2.2b1 on 2019-03-23 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0010_auto_20190323_1934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investment',
            name='efficency',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='investment',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=14, null=True),
        ),
    ]
