# Generated by Django 2.2b1 on 2019-03-24 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0011_auto_20190323_1948'),
    ]

    operations = [
        migrations.AddField(
            model_name='investmentimage',
            name='identifier',
            field=models.CharField(default='image', max_length=200, unique=True),
            preserve_default=False,
        ),
    ]
