# Generated by Django 2.2b1 on 2019-03-24 01:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0012_investmentimage_identifier'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investmentimage',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='investmentimage',
            name='title',
        ),
    ]
