# Generated by Django 2.2b1 on 2019-03-25 07:27

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0013_auto_20190324_0232'),
    ]

    operations = [
        migrations.AddField(
            model_name='investment',
            name='raw_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
    ]
