# Generated by Django 2.2b1 on 2019-03-31 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0015_auto_20190330_1655'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investmentimage',
            name='investment',
        ),
        migrations.AddField(
            model_name='investmentimage',
            name='investments',
            field=models.ManyToManyField(related_name='images', to='investments.Investment'),
        ),
    ]
