# Generated by Django 2.2b1 on 2019-03-31 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0016_auto_20190331_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investmentimage',
            name='image',
            field=models.ImageField(upload_to="uploads/investments"),
        ),
    ]
