# Generated by Django 2.2b1 on 2019-04-01 22:09

import autoslug.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0017_auto_20190331_1529'),
    ]

    operations = [
        migrations.AddField(
            model_name='investment',
            name='address_de',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='investment',
            name='address_en',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='investment',
            name='address_fr',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='investment',
            name='address_it',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='investment',
            name='description_de',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='investment',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='investment',
            name='description_fr',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='investment',
            name='description_it',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='investment',
            name='meta_de',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='investment',
            name='meta_en',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='investment',
            name='meta_fr',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='investment',
            name='meta_it',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='investment',
            name='slug_de',
            field=autoslug.fields.AutoSlugField(editable=False, null=True, populate_from='title', unique=True),
        ),
        migrations.AddField(
            model_name='investment',
            name='slug_en',
            field=autoslug.fields.AutoSlugField(editable=False, null=True, populate_from='title', unique=True),
        ),
        migrations.AddField(
            model_name='investment',
            name='slug_fr',
            field=autoslug.fields.AutoSlugField(editable=False, null=True, populate_from='title', unique=True),
        ),
        migrations.AddField(
            model_name='investment',
            name='slug_it',
            field=autoslug.fields.AutoSlugField(editable=False, null=True, populate_from='title', unique=True),
        ),
        migrations.AddField(
            model_name='investment',
            name='tags_de',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='investment',
            name='tags_en',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='investment',
            name='tags_fr',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='investment',
            name='tags_it',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='investment',
            name='title_de',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='investment',
            name='title_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='investment',
            name='title_fr',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='investment',
            name='title_it',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='investment',
            name='source',
            field=models.CharField(choices=[('caseinpiemonte', 'Case in Piemonte'), ('remicom', 'Remicom'), ('exploresardinia', 'Explore Sardinia'), ('sestrierecase', 'Sestriere case'), ('manual', 'Manuale')], default='manual', max_length=15),
        ),
    ]
