# Generated by Django 2.2b1 on 2019-04-01 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0018_auto_20190402_0009'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investment',
            name='address_de',
        ),
        migrations.RemoveField(
            model_name='investment',
            name='address_en',
        ),
        migrations.RemoveField(
            model_name='investment',
            name='address_fr',
        ),
        migrations.RemoveField(
            model_name='investment',
            name='address_it',
        ),
    ]
