# Generated by Django 2.2 on 2019-04-08 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0020_investment_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investment',
            name='country',
            field=models.CharField(choices=[('italy', 'Italia'), ('germany', 'Germania'), ('france', 'Francia'), ('switzerland', 'Svizzera')], default='italy', max_length=15),
        ),
    ]
