# Generated by Django 2.2 on 2019-04-11 08:05

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0021_auto_20190408_2200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investment',
            name='country',
            field=django_countries.fields.CountryField(default='IT', max_length=2),
        ),
    ]
