# Generated by Django 2.2 on 2019-04-16 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0022_auto_20190411_1005'),
    ]

    operations = [
        migrations.AddField(
            model_name='investment',
            name='surface',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True),
        ),
    ]
