# Generated by Django 2.2 on 2019-04-18 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0023_investment_surface'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investment',
            name='url',
            field=models.URLField(max_length=250, null=True),
        ),
    ]
