# Generated by Django 2.2 on 2019-05-24 21:41

from django.db import migrations
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0024_auto_20190418_1638'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investment',
            name='description_de',
        ),
        migrations.RemoveField(
            model_name='investment',
            name='description_fr',
        ),
        migrations.RemoveField(
            model_name='investment',
            name='meta_de',
        ),
        migrations.RemoveField(
            model_name='investment',
            name='meta_fr',
        ),
        migrations.RemoveField(
            model_name='investment',
            name='slug_de',
        ),
        migrations.RemoveField(
            model_name='investment',
            name='slug_fr',
        ),
        migrations.RemoveField(
            model_name='investment',
            name='tags_de',
        ),
        migrations.RemoveField(
            model_name='investment',
            name='tags_fr',
        ),
        migrations.RemoveField(
            model_name='investment',
            name='title_de',
        ),
        migrations.RemoveField(
            model_name='investment',
            name='title_fr',
        ),
        migrations.AlterField(
            model_name='investmentimage',
            name='image',
            field=sorl.thumbnail.fields.ImageField(upload_to='images'),
        ),
    ]
