# Generated by Django 2.2 on 2019-05-25 01:58

from django.db import migrations
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0026_auto_20190525_0344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investmentimage',
            name='image',
            field=sorl.thumbnail.fields.ImageField(upload_to='uploads'),
        ),
    ]
