# Generated by Django 2.2 on 2019-05-25 02:15

from django.db import migrations
import investments.models
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0027_auto_20190525_0358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investmentimage',
            name='image',
            field=sorl.thumbnail.fields.ImageField(upload_to="uploads/investments"),
        ),
    ]
