# Generated by Django 2.2 on 2019-05-25 10:51

from django.db import migrations, models
import investments.models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0028_auto_20190525_0415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investmentimage',
            name='image',
		    field=models.ImageField(upload_to="uploads/investments"),
        ),
    ]
