# Generated by Django 2.2 on 2019-07-31 18:32

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0029_auto_20190525_1251'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investment',
            name='raw_data',
        ),
        migrations.RemoveField(
            model_name='investment',
            name='surface',
        ),
        migrations.RemoveField(
            model_name='investment',
            name='identifier',
        ),
        migrations.RemoveField(
            model_name='investment',
            name='address',
        ),
        migrations.CreateModel(
            name='P2PLending',
            fields=[
                ('investment_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='investments.Investment')),
                ('buyback', models.BooleanField()),
            ],
            options={
                'verbose_name': 'Peer to peer lending investment',
                'verbose_name_plural': 'Peer to peer lending investments',
            },
            bases=('investments.investment',),
        ),
        migrations.CreateModel(
            name='RealEstate',
            fields=[
                ('investment_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='investments.Investment')),
                ('address', models.CharField(max_length=500, null=True)),
                ('surface', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('raw_data', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
                ('identifier', models.CharField(blank=True, max_length=200, null=True, unique=True)),
            ],
            options={
                'verbose_name': 'Real estate investment',
                'verbose_name_plural': 'Real estate investments',
            },
            bases=('investments.investment',),
        ),
        migrations.AlterModelOptions(
            name='investmentimage',
            options={'verbose_name': 'Investment image', 'verbose_name_plural': 'Investment images'},
        ),
        migrations.RemoveField(
            model_name='investment',
            name='country',
        ),
        migrations.RemoveField(
            model_name='investment',
            name='meta',
        ),
        migrations.RemoveField(
            model_name='investment',
            name='meta_en',
        ),
        migrations.RemoveField(
            model_name='investment',
            name='meta_it',
        ),
        migrations.RemoveField(
            model_name='investment',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='investment',
            name='tags_en',
        ),
        migrations.RemoveField(
            model_name='investment',
            name='tags_it',
        ),
        migrations.AddField(
            model_name='investment',
            name='countries',
            field=django_countries.fields.CountryField(default='IT', max_length=2),
        ),
        migrations.AddField(
            model_name='investment',
            name='interests',
            field=models.DecimalField(decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AlterField(
            model_name='investment',
            name='category',
            field=models.CharField(choices=[('investment', 'Investment'), ('realestate', 'Real estate'), ('p2plending', 'P2P lending')], max_length=15),
        ),
        migrations.AlterField(
            model_name='investmentimage',
            name='identifier',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
    ]
