# Generated by Django 2.2 on 2019-08-01 08:04

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0030_auto_20190731_2032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investment',
            name='category',
            field=models.CharField(choices=[('realestate', 'Real estate'), ('p2plending', 'P2P lending')], max_length=15),
        ),
        migrations.AlterField(
            model_name='investment',
            name='countries',
            field=django_countries.fields.CountryField(default='IT', max_length=23, multiple=True),
        ),
    ]
