# Generated by Django 2.2 on 2019-08-01 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0031_auto_20190801_1004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investment',
            name='currency',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='investment',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='investment',
            name='description_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='investment',
            name='description_it',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='investment',
            name='interests',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AlterField(
            model_name='investment',
            name='url',
            field=models.URLField(blank=True, max_length=250, null=True),
        ),
    ]
