# Generated by Django 2.2 on 2019-08-08 22:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0034_auto_20190808_1842'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bond',
            fields=[
                ('investment_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='investments.Investment')),
            ],
            options={
                'verbose_name': 'Bond investment',
                'verbose_name_plural': 'Bonds investments',
            },
            bases=('investments.investment',),
        ),
        migrations.CreateModel(
            name='Commodity',
            fields=[
                ('investment_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='investments.Investment')),
            ],
            options={
                'verbose_name': 'Commodity investment',
                'verbose_name_plural': 'Commodities investments',
            },
            bases=('investments.investment',),
        ),
        migrations.CreateModel(
            name='Equity',
            fields=[
                ('investment_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='investments.Investment')),
            ],
            options={
                'verbose_name': 'Equity investment',
                'verbose_name_plural': 'Equities investments',
            },
            bases=('investments.investment',),
        ),
        migrations.CreateModel(
            name='HedgeFund',
            fields=[
                ('investment_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='investments.Investment')),
            ],
            options={
                'verbose_name': 'Hedge fund investment',
                'verbose_name_plural': 'Hedge funds investments',
            },
            bases=('investments.investment',),
        ),
        migrations.CreateModel(
            name='PreciousObject',
            fields=[
                ('investment_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='investments.Investment')),
            ],
            options={
                'verbose_name': 'Precious object investment',
                'verbose_name_plural': 'Precious objects investments',
            },
            bases=('investments.investment',),
        ),
        migrations.AlterField(
            model_name='investment',
            name='category',
            field=models.CharField(choices=[('realestate', 'Real estate'), ('p2plending', 'P2P lending'), ('business', 'Business'), ('precious', 'Precious objects'), ('hedge', 'Hedge funds'), ('bond', 'Bonds'), ('commodity', 'Commodities'), ('equity', 'Equities')], max_length=15),
        ),
    ]
