# Generated by Django 2.2 on 2019-08-09 08:09

import django.contrib.postgres.fields.ranges
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0035_auto_20190809_0036'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investment',
            name='interests',
        ),
        migrations.RemoveField(
            model_name='investment',
            name='price',
        ),
        migrations.AddField(
            model_name='investment',
            name='interest',
            field=django.contrib.postgres.fields.ranges.DecimalRangeField(null=True),
        ),
    ]
