# Generated by Django 2.2 on 2019-08-09 08:09

import django.contrib.postgres.fields.ranges
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0036_auto_20190809_1009'),
    ]

    operations = [
        migrations.AddField(
            model_name='investment',
            name='price',
            field=django.contrib.postgres.fields.ranges.DecimalRangeField(null=True),
        ),
    ]
