# Generated by Django 2.2 on 2019-04-11 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('economics_data', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='timeserieentry',
            old_name='price',
            new_name='value',
        ),
    ]
