# Generated by Django 2.2 on 2019-04-11 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('economics_data', '0002_auto_20190411_1323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeserie',
            name='slug',
            field=models.SlugField(),
        ),
    ]
