# Generated by Django 2.2 on 2019-04-15 00:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('economics_data', '0003_auto_20190411_1328'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='timeserieentry',
            options={'ordering': ['date']},
        ),
    ]
